include_guard(GLOBAL)

if (PROJECT_IS_TOP_LEVEL)

    # ------------------------------
    # Heliogrim Global Build Options
    # ------------------------------

    option(HELIOGRIM_USE_MAIN_THREAD_INJECTION "USE_MAIN_THREAD_INJECTION" OFF)
    option(HELIOGRIM_PREVENT_MAIN_AUTO_SLEEP "PREVENT_MAIN_AUTO_SLEEP" OFF)

    # ------------------------------

else ()
    # Auto-Sanitize for Sub-Modules
    if (NOT DEFINED HELIOGRIM_USE_MAIN_THREAD_INJECTION OR NOT DEFINED CACHE{HELIOGRIM_USE_MAIN_THREAD_INJECTION})
        set(HELIOGRIM_USE_MAIN_THREAD_INJECTION OFF CACHE INTERNAL "USE_MAIN_THREAD_INJECTION")
    endif ()
    if (NOT DEFINED HELIOGRIM_PREVENT_MAIN_AUTO_SLEEP OR NOT DEFINED CACHE{HELIOGRIM_PREVENT_MAIN_AUTO_SLEEP})
        set(HELIOGRIM_PREVENT_MAIN_AUTO_SLEEP OFF CACHE INTERNAL "PREVENT_MAIN_AUTO_SLEEP")
    endif ()
endif ()